events.h: add missing functional include
:Release Notes:
Fix build.

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/527952
audiod/1.0.0-57-r32/git/include/events.h:183:14: error: 'function' in namespace 'std' does not name a template type
audiod/1.0.0-57-r32/git/src/modules/deviceManager/deviceManager.cpp:1128:71: error: 'struct events::EVENT_REQUEST_INTERNAL_DEVICES_INFO_T' has no member named 'func'
audiod/1.0.0-57-r32/git/src/modules/masterVolumeManager/OSEMasterVolumeManager.cpp:2425:35: error: 'struct events::EVENT_REQUEST_INTERNAL_DEVICES_INFO_T' has no member named 'func'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-6543] CCC: Various build fixes

Upstream-Status: Submitted [http://gpro.lge.com/c/webosose/audiod-pro/+/344272 events.h: add missing functional include ]
Change-Id: Ia09aa6ae7728001c955005bae74494e244d233b4
Reviewed-on: http://gpro.lge.com/c/webosose/audiod-pro/+/344272
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Sushovan Gangopadhy <sushovan.g@lge.com>
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>
Tested-by: Sushovan Gangopadhy <sushovan.g@lge.com>