Fix luna-service2 usage
:Release Notes:
Since luna-service2 submission 143 from September 2012 ls2 headers
should be included from luna-service2 directory.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/548219

FAILED: CMakeFiles/audiod.dir/src/AudiodCallbacks.cpp.o
TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DAUDIOD_PALM_LEGACY -DAUDIOD_TEST_API -DENABLE_POWEROFF_REBOOT_SIGNAL -DENABLE_WAKELOCK_FOR_SLEEP_STATE -DHAS_LTTNG -DSYSTEMSOUNDS_PATH=\"/media/internal/systemsounds/\" -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot/usr/include/json-c -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/umi -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/umi/modules -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/umi/soundSettings -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/controls -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/controls/hardware -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/controls/pulse -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/modules -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/include/public -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/include -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33=/usr/src/debug/audiod/1.0.0-161.pro.9-r33                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33=/usr/src/debug/audiod/1.0.0-161.pro.9-r33                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot-native=  -fvisibility-inlines-hidden  -Wno-narrowing -DAUDIOD_IPC_SERVER -DBOOST_DISABLE_THREADS -D_GNU_SOURCE -Wall -DWEBOS_TARGET_MACHINE_RASPBERRYPI4 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot/usr/lib/glib-2.0/include -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/recipe-sysroot/usr/lib/glib-2.0/include -DUSE_PMLOG_DECLARATION -D_REENTRANT -D_REENTRANT -DNDEBUG -MD -MT CMakeFiles/audiod.dir/src/AudiodCallbacks.cpp.o -MF CMakeFiles/audiod.dir/src/AudiodCallbacks.cpp.o.d -o CMakeFiles/audiod.dir/src/AudiodCallbacks.cpp.o -c TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/AudiodCallbacks.cpp
In file included from TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/AudiodCallbacks.h:25,
                 from TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/AudiodCallbacks.cpp:20:
TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/audiod/1.0.0-161.pro.9-r33/git/src/controls/AudioMixer.h:24:10: fatal error: lunaservice.h: No such file or directory
   24 | #include <lunaservice.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

...

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-10642] Remove the temporary work around from 2012 from luna-service2 recipe
[WRP-11224] audiod: Fix luna-service2 usage
[WRP-10791] CCC: Various build fixes

Change-Id: I83616fae6fe3f4729e356f720bd93fe1bf537ade
Reviewed-on: http://gpro.lge.com/c/webosose/audiod-pro/+/348186
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Sushovan Gangopadhy <sushovan.g@lge.com>
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>
Tested-by: Sushovan Gangopadhy <sushovan.g@lge.com>